version: "3"
services:
  wherehows-postgres:
    image: "wherehows-postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${WHZ_DB_NAME}
      POSTGRES_USER: ${WHZ_DB_USERNAME}
      POSTGRES_PASSWORD: ${WHZ_DB_PASSWORD}
  wherehows-elasticsearch:
    image: "linkedin/wherehows-elasticsearch:latest"
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
  wherehows-backend:
    image: "linkedin/wherehows-backend:latest"
    ports:
      - 19001:9000
    environment:
      WHZ_SECRET: ${WHZ_SECRET}
      WHZ_DB_USERNAME: ${WHZ_DB_USERNAME}
      WHZ_DB_PASSWORD: ${WHZ_DB_PASSWORD}
      WHZ_DB_URL: jdbc:postgresql://wherehows-postgres:5432/${WHZ_DB_NAME}?user=${WHZ_DB_USERNAME}&password=${WHZ_DB_PASSWORD}
    command: dockerize -wait tcp://wherehows-postgres:5432 -timeout 120s bin/playBinary
    links:
      - "wherehows-postgres:wherehows-postgres"
  wherehows-frontend:
    image: "linkedin/wherehows-frontend:latest"
    ports:
      - 9001:9000
    environment:
      WHZ_SECRET: ${WHZ_SECRET}
      WHZ_DB_USERNAME: ${WHZ_DB_USERNAME}
      WHZ_DB_PASSWORD: ${WHZ_DB_PASSWORD}
      WHZ_DB_URL: jdbc:postgresql://wherehows-postgres:5432/${WHZ_DB_NAME}?user=${WHZ_DB_USERNAME}&password=${WHZ_DB_PASSWORD}
      WHZ_SEARCH_ENGINE: ${WHZ_SEARCH_ENGINE}
      WHZ_ES_DATASET_URL: ${WHZ_ES_DATASET_URL}
      WHZ_ES_METRIC_URL: ${WHZ_ES_METRIC_URL}
      WHZ_ES_FLOW_URL: ${WHZ_ES_FLOW_URL}
      WHZ_LDAP_URL: ${WHZ_LDAP_URL}
      WHZ_LDAP_PRINCIPAL_DOMAIN: ${WHZ_LDAP_PRINCIPAL_DOMAIN}
      WHZ_LDAP_SEARCH_BASE: ${WHZ_LDAP_SEARCH_BASE}
    command: dockerize -wait tcp://wherehows-postgres:5432 -wait http://wherehows-elasticsearch:9200 -timeout 120s bin/playBinary
    links:
      - "wherehows-postgres:wherehows-postgres"
      - "wherehows-elasticsearch:wherehows-elasticsearch"